# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=200)),
                ('taskType', models.IntegerField()),
                ('userName', models.CharField(max_length=30)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='savetime')),
            ],
        ),
    ]
